%global tl_name atkinson
%global tl_revision 77682

Name:		texlive-%{tl_name}
Version:	%{tl_revision}
Release:	1
Summary:	Support for the Atkinson Hyperlegible family of fonts
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/fonts/atkinson
License:	lppl other-free
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/atkinson.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/atkinson.doc.r%{tl_revision}.tar.xz
BuildArch:	noarch
Requires(pre):	texlive-tlpkg
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
This package provides LaTeX, pdfLaTeX, XeLaTeX and LuaLaTeX support for
the Atkinson Hyperlegible family of fonts, named after Braille Institute
founder, J. Robert Atkinson. What makes it different from traditional
typography design is that it focuses on letterform distinction to
increase character recognition, ultimately improving readability.

%prep
%setup -q -c -a1
rm -rf tlpkg
if [ -d RELOC ]; then
	cp -a RELOC/. .
	rm -rf RELOC
fi

%build

%install
mkdir -p %{buildroot}%{_datadir}/texmf-dist
# Flat tlnet layout: tex/ doc/ source/ fonts/ ... -> texmf-dist/
if [ -d texmf-dist ]; then
	cp -a texmf-dist/. %{buildroot}%{_datadir}/texmf-dist/
elif [ -d texmf ]; then
	mkdir -p %{buildroot}%{_datadir}/texmf
	cp -a texmf/. %{buildroot}%{_datadir}/texmf/
else
	for d in * .[!.]* ..?*; do
		[ -e "$d" ] || continue
		case "$d" in tlpkg|RELOC) continue ;; esac
		cp -a "$d" %{buildroot}%{_datadir}/texmf-dist/
	done
fi
rm -rf %{buildroot}%{_datadir}/texmf-dist/tlpkg

%files
%dir %{_datadir}/texmf-dist
%dir %{_datadir}/texmf-dist/doc
%dir %{_datadir}/texmf-dist/fonts
%dir %{_datadir}/texmf-dist/tex
%dir %{_datadir}/texmf-dist/doc/fonts
%dir %{_datadir}/texmf-dist/fonts/enc
%dir %{_datadir}/texmf-dist/fonts/map
%dir %{_datadir}/texmf-dist/fonts/opentype
%dir %{_datadir}/texmf-dist/fonts/tfm
%dir %{_datadir}/texmf-dist/fonts/type1
%dir %{_datadir}/texmf-dist/fonts/vf
%dir %{_datadir}/texmf-dist/tex/latex
%dir %{_datadir}/texmf-dist/doc/fonts/atkinson
%dir %{_datadir}/texmf-dist/fonts/enc/dvips
%dir %{_datadir}/texmf-dist/fonts/map/dvips
%dir %{_datadir}/texmf-dist/fonts/opentype/public
%dir %{_datadir}/texmf-dist/fonts/tfm/public
%dir %{_datadir}/texmf-dist/fonts/type1/public
%dir %{_datadir}/texmf-dist/fonts/vf/public
%dir %{_datadir}/texmf-dist/tex/latex/atkinson
%dir %{_datadir}/texmf-dist/fonts/enc/dvips/atkinson
%dir %{_datadir}/texmf-dist/fonts/map/dvips/atkinson
%dir %{_datadir}/texmf-dist/fonts/opentype/public/atkinson
%dir %{_datadir}/texmf-dist/fonts/tfm/public/atkinson
%dir %{_datadir}/texmf-dist/fonts/type1/public/atkinson
%dir %{_datadir}/texmf-dist/fonts/vf/public/atkinson
%doc %{_datadir}/texmf-dist/doc/fonts/atkinson/Atkinson-Hyperlegible-Font-License-2020-1104.pdf
%doc %{_datadir}/texmf-dist/doc/fonts/atkinson/BIA_AtkinsonHyerlegible-Specimen_200210.pdf
%doc %{_datadir}/texmf-dist/doc/fonts/atkinson/README
%doc %{_datadir}/texmf-dist/doc/fonts/atkinson/atkinson-samples.pdf
%doc %{_datadir}/texmf-dist/doc/fonts/atkinson/atkinson-samples.tex
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_2euc5w.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_7pe33p.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_bbsfwk.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_bxlfxu.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_ehsai2.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_ghg2ik.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_gjro6p.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_k53f2f.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_sxa7r4.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsn_tlrdxq.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsnmono_2euc5w.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsnmono_bbsfwk.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsnmono_bxlfxu.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsnmono_ehsai2.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsnmono_ghg2ik.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsnmono_k53f2f.enc
%{_datadir}/texmf-dist/fonts/enc/dvips/atkinson/atkinsnmono_sxa7r4.enc
%{_datadir}/texmf-dist/fonts/map/dvips/atkinson/atkinson.map
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-Bold.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-BoldItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-ExtraBold.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-ExtraBoldItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-ExtraLight.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-ExtraLightItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-Light.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-LightItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-Medium.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-MediumItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-Regular.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-RegularItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-SemiBold.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleMono-SemiBoldItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-Bold.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-BoldItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-ExtraBold.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-ExtraBoldItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-ExtraLight.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-ExtraLightItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-Light.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-LightItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-Medium.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-MediumItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-Regular.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-RegularItalic.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-SemiBold.otf
%{_datadir}/texmf-dist/fonts/opentype/public/atkinson/AtkinsonHyperlegibleNext-SemiBoldItalic.otf
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Bold-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-BoldItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBold-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraBoldItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLight-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-ExtraLightItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Light-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-LightItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Medium-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-MediumItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-Regular-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-RegularItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBold-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-lf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-lf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-lf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-lf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-lf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-lf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-lf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsn-SemiBoldItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Bold-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-BoldItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBold-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLight-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Light-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-LightItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Medium-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-MediumItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-Regular-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-RegularItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBold-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-sup-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-sup-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-sup-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-sup-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-sup-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-ly1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-ly1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-ot1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-t1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-t1.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-ts1--base.tfm
%{_datadir}/texmf-dist/fonts/tfm/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-ts1.tfm
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-Bold.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-BoldItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-ExtraBold.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-ExtraBoldItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-ExtraLight.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-ExtraLightItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-Light.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-LightItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-Medium.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-MediumItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-Regular.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-RegularItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-SemiBold.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsn-SemiBoldItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-Bold.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-BoldItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-ExtraBold.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-ExtraBoldItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-ExtraLight.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-ExtraLightItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-Light.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-LightItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-Medium.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-MediumItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-Regular.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-RegularItalic.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-SemiBold.pfb
%{_datadir}/texmf-dist/fonts/type1/public/atkinson/atkinsnmono-SemiBoldItalic.pfb
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Bold-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Bold-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Bold-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Bold-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Bold-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Bold-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Bold-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Bold-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-BoldItalic-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-BoldItalic-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-BoldItalic-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-BoldItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-BoldItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-BoldItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-BoldItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-BoldItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBold-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBold-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBold-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBold-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBold-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBold-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBold-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBold-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBoldItalic-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBoldItalic-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBoldItalic-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBoldItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBoldItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBoldItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBoldItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraBoldItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLight-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLight-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLight-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLight-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLight-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLight-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLight-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLight-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLightItalic-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLightItalic-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLightItalic-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLightItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLightItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLightItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLightItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-ExtraLightItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Light-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Light-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Light-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Light-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Light-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Light-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Light-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Light-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-LightItalic-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-LightItalic-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-LightItalic-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-LightItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-LightItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-LightItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-LightItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-LightItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Medium-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Medium-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Medium-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Medium-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Medium-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Medium-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Medium-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Medium-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-MediumItalic-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-MediumItalic-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-MediumItalic-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-MediumItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-MediumItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-MediumItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-MediumItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-MediumItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Regular-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Regular-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Regular-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Regular-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Regular-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Regular-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Regular-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-Regular-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-RegularItalic-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-RegularItalic-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-RegularItalic-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-RegularItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-RegularItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-RegularItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-RegularItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-RegularItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBold-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBold-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBold-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBold-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBold-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBold-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBold-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBold-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBoldItalic-lf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBoldItalic-lf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBoldItalic-lf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBoldItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBoldItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBoldItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBoldItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsn-SemiBoldItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Bold-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Bold-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Bold-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Bold-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Bold-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-BoldItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-BoldItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-BoldItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-BoldItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-BoldItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBold-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBold-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBold-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBold-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBold-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBoldItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBoldItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraBoldItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLight-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLight-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLight-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLight-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLight-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLightItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLightItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-ExtraLightItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Light-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Light-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Light-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Light-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Light-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-LightItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-LightItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-LightItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-LightItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-LightItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Medium-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Medium-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Medium-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Medium-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Medium-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-MediumItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-MediumItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-MediumItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-MediumItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-MediumItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Regular-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Regular-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Regular-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Regular-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-Regular-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-RegularItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-RegularItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-RegularItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-RegularItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-RegularItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBold-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBold-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBold-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBold-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBold-tlf-ts1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBoldItalic-sup-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBoldItalic-sup-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-ly1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-t1.vf
%{_datadir}/texmf-dist/fonts/vf/public/atkinson/atkinsnmono-SemiBoldItalic-tlf-ts1.vf
%{_datadir}/texmf-dist/tex/latex/atkinson/LY1atkinsn-LF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/LY1atkinsn-Sup.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/LY1atkinsn-TLF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/LY1atkinsnmono-Sup.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/LY1atkinsnmono-TLF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/OT1atkinsn-LF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/OT1atkinsn-Sup.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/OT1atkinsn-TLF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/OT1atkinsnmono-Sup.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/OT1atkinsnmono-TLF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/T1atkinsn-LF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/T1atkinsn-Sup.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/T1atkinsn-TLF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/T1atkinsnmono-Sup.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/T1atkinsnmono-TLF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/TS1atkinsn-LF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/TS1atkinsn-TLF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/TS1atkinsnmono-TLF.fd
%{_datadir}/texmf-dist/tex/latex/atkinson/atkinson.sty
